apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  labels:
    app: faas-srv
  name: faas-srv
spec:
  annotations:
    sidecar.istio.io/nativeSidecar: 'true'
  env:
    - name: CHERRYPY_NUMTHREADS
      value: '100'
    - name: FUNC_TIMEOUT
      value: '1800'
    - name: MISTRAL_API_KEY
      value: {{ .Values.mistralApiKey }}
    - name: MISTRAL_MODEL
      value: open-mistral-7b
    - name: SERVICE_BINDING_ROOT
      value: /bindings
  resourceConfiguration:
    function:
      profile: S
  runtime: python312
  runtimeImageOverride: tiosouji/faas:py-312
  scaleConfig:
    maxReplicas: 1
    minReplicas: 1
  secretMounts:
    # - mountPath: /bindings/mypythonapp-dest
    #   secretName: app-dest-binding-secret
    # - mountPath: /bindings/kyma-poster-aws-dest
    #   secretName: kyma-poster-aws-dest-binding-secret
    # - mountPath: /bindings/app-hdi
    #   secretName: app-hdi-binding-secret
  source:
    gitRepository:
      auth:
        secretName: git-basic-secret
        type: basic
      baseDir: /mypythonapp/faas/srv/
      reference: main
      url: https://github.tools.sap/fp-stakeholder-management/monty-python.git
